### PR TITLE
Support custom prefix (/usr) and sysconfdir (/etc)

### LINKED ISSUE #25: Installing hass.io on TorizonCore
Hi,

I tried to install hass.io on TorizonCore on an Apalis iMX8. After making sure that my base system has the right tools pre-installed (jq and curl were missing), I was able to run the installer. However, it stopped pretty quickly:

```
# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -m qemuarm-64
[Warning] No AppArmor support on host.
mkdir: cannot create directory '/usr/share/hassio': Read-only file system
```

This is due to the nature that the base system is using OSTree which makes /usr Read-only. Is it possible to install the binaries to a different location (e.g. `/var`?). `/etc` is write able, so only the files stored in `/usr` are an issue.

### PR DESCRIPTION
**Pull request by agners**
This refactors the path replacement a bit and uses @VARIABLE@ in the templates to make replacement easier to follow and safe in case of multiple similar paths. With that one can use a custom location for /usr or /etc, e.g.

```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -p /usr/local -s /usr/local/etc/
```

Closes #25.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @agners, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-installer#27).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @agners, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-installer#27).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @agners, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-installer#27).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by agners** [comment]
@pvizeli gentle ping.

**Comment by pvizeli** [comment]
Thanks

**Pull request merged**
